name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main # Déclenchement lorsque le code est poussé sur main
    paths:
      - 'src/backend/**'

env:
  REG_NAME: acrfi21210.azurecr.io   # Nom de la registry
  IMAGE_NAME: backend-app-git       # Nom de votre image


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login Docker sur la registry
      - name: Docker login
        run: |
          echo ${{ secrets.AZURE_PASSWORD }} | docker login ${{ env.REG_NAME }} -u ${{ secrets.AZURE_USERNAME }} --password-stdin

      # 3️⃣ Build de l'image Docker avec le tag latest
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:latest ./src/backend

      # 4️⃣ Push de l'image sur la registry
      - name: Push Docker image
        run: |
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:latest