name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main # Déclenchement lorsque le code est poussé sur main
    paths:
      - 'src/backend/**'

env:
  REGISTRY: acrfi21210.azurecr.io   # Nom de la registry
  IMAGE_NAME: todo-backend-git-mah      # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️ Login Docker sur la registry
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      # 3️ Build de l'image Docker avec le tag latest
      - name: Build Docker image
        run: |
          echo "Building image with SHA tag and latest tag..."
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
                       -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ./src/backend

      # 4️ Push de l'image sur la registry
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest